### ISSUE TITLE
NPE or hangs in ConnectionPool

### ISSUE THREAD

**Issue by adamdickmeiss** [eclipse-vertx/vertx-sql-client#823] opened 2020-12-01 09:31 UTC
### Version

vertx-sq-client 4.0.0-SNAPSHOT   commit 4a90fc5f1c30041b6eea3304760f0cb50acde9c3

### Context

While perform a large batch import test in https://github.com/folio-org/mod-inventory-storage of FOLIO we get NPEs or hangs.. For the NPE we get traces like these:

```
java.lang.NullPointerException: null
        at io.vertx.sqlclient.impl.pool.ConnectionPool.check(ConnectionPool.java:260) ~[vertx-sql-client-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at io.vertx.sqlclient.impl.pool.ConnectionPool.release(ConnectionPool.java:245) ~[vertx-sql-client-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at io.vertx.sqlclient.impl.pool.ConnectionPool.access$200(ConnectionPool.java:44) ~[vertx-sql-client-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at io.vertx.sqlclient.impl.pool.ConnectionPool$PooledConnection.doClose(ConnectionPool.java:198) ~[vertx-sql-client-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at io.vertx.sqlclient.impl.pool.ConnectionPool$PooledConnection.lambda$close$0(ConnectionPool.java:179) ~[vertx-sql-client-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:78) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.WorkerContext.execute(WorkerContext.java:113) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.WorkerContext.emit(WorkerContext.java:77) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:294) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.WorkerContext.emit(WorkerContext.java:25) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:49) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.WorkerContext.emit(WorkerContext.java:25) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.sqlclient.impl.pool.ConnectionPool$PooledConnection.close(ConnectionPool.java:179) ~[vertx-sql-client-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at io.vertx.sqlclient.impl.SqlConnectionImpl.close(SqlConnectionImpl.java:149) ~[vertx-sql-client-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at io.vertx.sqlclient.impl.SqlConnectionImpl.close(SqlConnectionImpl.java:134) ~[vertx-sql-client-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.folio.rest.persist.PostgresClient.finalizeTx(PostgresClient.java:645) ~[domain-models-runtime-32.0.0-SNAPSHOT.jar:?]
        at org.folio.rest.persist.PostgresClient.lambda$7(PostgresClient.java:687) ~[domain-models-runtime-32.0.0-SNAPSHOT.jar:?]
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:125) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:61) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:180) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.sqlclient.impl.TransactionImpl.lambda$wrapAndSchedule$0(TransactionImpl.java:90) ~[vertx-sql-client-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:125) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:53) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.WorkerContext.execute(WorkerContext.java:113) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.WorkerContext.execute(WorkerContext.java:66) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.WorkerContext.execute(WorkerContext.java:84) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:199) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:50) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:180) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.pgclient.impl.PgSocketConnection.lambda$doSchedule$2(PgSocketConnection.java:154) ~[vertx-pg-client-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at io.vertx.sqlclient.impl.command.CommandResponse.fire(CommandResponse.java:46) ~[vertx-sql-client-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at io.vertx.sqlclient.impl.SocketConnectionBase.handleMessage(SocketConnectionBase.java:255) ~[vertx-sql-client-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at io.vertx.pgclient.impl.PgSocketConnection.handleMessage(PgSocketConnection.java:99) ~[vertx-pg-client-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:93) ~[vertx-sql-client-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at io.vertx.core.net.impl.NetSocketImpl.lambda$new$2(NetSocketImpl.java:97) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.net.impl.NetSocketImpl.lambda$handleMessage$10(NetSocketImpl.java:382) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:78) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:123) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.49.Final.jar:4.1.49.Final]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

By adding log statements, it is clear that ``waiter = waiters.poll`` returns null and results in NPE in the line that follows.

### Do you have a reproducer?

So far it's been hard to make (small) a reproducer for this. This is a cumbersome way to reproduce:

clone https://github.com/folio-org/raml-module-builder/tree/RMB-609

clone https://github.com/folio-org/mod-inventory-storage/tree/connection-pool-npe

For each project:

git submodule init 
git submodule update
mvn -B install

Tests for mod-inventory-storage will sometimes timeout.. and only in some of those cases - exceptions will be thrown.

### Related

Could be related to commit 30be4a2d2476cdc3c2e0c01826c79478f7cc35bc and commit 4ce65f3e87ec4dc8cc48de03ecc8cd3c17f48f3c .

**Comment by vietj** [comment] 2020-12-01 10:23
it seems that you are using a worker verticle ?

**Comment by vietj** [comment] 2020-12-01 10:27
I opened this issue https://github.com/eclipse-vertx/vertx-sql-client/issues/825

**Comment by adamdickmeiss** [comment] 2020-12-01 10:36
I don't think we are.. One verticle is created for the test.. I don't see any extra.. no executeBlocking  .. But a lot of runOnContext here and there.

**Comment by vietj** [comment] 2020-12-01 11:54
can you check ? I can see in the stack trace:

```
at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:78) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
at io.vertx.core.impl.WorkerContext.execute(WorkerContext.java:113) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
at io.vertx.core.impl.WorkerContext.emit(WorkerContext.java:77) ~[vertx-core-4.0.0.CR2.jar:4.0.0.CR2]
```

**Comment by adamdickmeiss** [comment] 2020-12-01 13:16
Found it.

https://github.com/folio-org/mod-inventory-storage/blob/a259fa99d89dddd9c509d319754e20e9e4457b24/src/test/java/org/folio/rest/api/StorageTestSuite.java#L139

I'll see if removing that makes it single-threaded again.

**Comment by adamdickmeiss** [comment] 2020-12-01 13:40
I'm happy to close this. Using a worker Verticle would be fine if that was isolated.. But I can see accesses to the Connection Pool from other places than within this Verticle.. That's of course a very bad idea.

**Comment by vietj** [comment] 2020-12-01 15:33
SQL client pool should support usage from worker vertices, so I'll add
tests for this and make sure it works correctly too.

**Comment by ashertarno** [comment] 2021-01-13 14:33
hi guys, it seems we started to run into the same problem. it's hard to me to create a stand alone reproducer, but while running on a huge system with a number of connection pools we started to see the errors below. the pool seems to be totally stuck once this occurs, so it's a total show stopper. we are running on 3.9.4, no workers involved

`[io.vertx.core.impl.ContextImpl|vert.x-eventloop-thread-1]  Unhandled exception
                                                      java.lang.NullPointerException
                                                              at io.vertx.sqlclient.impl.ConnectionPool.check(ConnectionPool.java:202)
                                                              at io.vertx.sqlclient.impl.ConnectionPool.access$500(ConnectionPool.java:35)
                                                              at io.vertx.sqlclient.impl.ConnectionPool$PooledConnection.handleClosed(ConnectionPool.java
:153)
                                                              at io.vertx.sqlclient.impl.SocketConnectionBase.handleClose(SocketConnectionBase.java:318)
                                                              at io.vertx.sqlclient.impl.SocketConnectionBase.handleException(SocketConnectionBase.java:2
98)
                                                              at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:88)
                                                              at io.vertx.core.net.impl.NetSocketImpl.lambda$new$2(NetSocketImpl.java:101)
                                                              at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
                                                              at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
                                                              at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:357)
                                                              at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
                                                              at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
                                                              at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
                                                              at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:163)
                                                              at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ontext.java:379)
                                                              at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ontext.java:365)
                                                              at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
                                                              at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
                                                              at io.vertx.pgclient.impl.codec.PgEncoder.lambda$write$0(PgEncoder.java:78)
                                                              at io.vertx.pgclient.impl.codec.PgCommandCodec.handleReadyForQuery(PgCommandCodec.java:138)
                                                              at io.vertx.pgclient.impl.codec.PgDecoder.decodeReadyForQuery(PgDecoder.java:226)
                                                              at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:86)
                                                              at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
                                                              at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                                                              at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                                                              at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
                                                              at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
                                                              at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                                                              at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
															  ontext.java:365)
                                                              at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
                                                              at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
                                                              at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
                                                              at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
                                                              at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
                                                              at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
                                                              at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
                                                              at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                                                              at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                                                              at java.lang.Thread.run(Thread.java:748)`

**Comment by ashertarno** [comment] 2021-01-18 11:03
i found a place that actually calls the dbpool from a worker thread. the npe is getting thrown when the next call (on the event-loop) after the one made from the worker thread is accessing the db connection pool. looks like this is indeed the issue described here.

**Comment by underkin** [comment] 2021-02-01 18:30
Hi guys,

I'm also being affected by this one. We are using worker vertices and as @vietj  mention, it is intended that we can use from a worker verticle.
Is there any workaround we can use until this get fixed? (other that not using worker verticle), or any idea when a fix for this will  get released?

Kind regards

**Comment by vietj** [comment] 2021-02-01 22:54
it should work from worker thread in 4.0.1 release that will be done soon.

can you try with 4.0.1 SNAPSHOTS ?

**Comment by underkin** [comment] 2021-02-02 11:33
I used the 4.0.1 SNAPSHOT, but I'm still getting the same stacktrace when running from a worked verticle:

 ```
2021-02-02 10:31:03,249 [vert.x-worker-thread-17] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
 java.lang.NullPointerException: null
 	at io.vertx.sqlclient.impl.pool.ConnectionPool.check(ConnectionPool.java:260)
 	at io.vertx.sqlclient.impl.pool.ConnectionPool.doAcquire(ConnectionPool.java:103)
 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
 	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:78)
 	at io.vertx.core.impl.WorkerContext.execute(WorkerContext.java:113)
 	at io.vertx.core.impl.WorkerContext.emit(WorkerContext.java:77)
 	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:294)
 	at io.vertx.core.impl.WorkerContext.emit(WorkerContext.java:25)
 	at io.vertx.sqlclient.impl.pool.ConnectionPool.acquire(ConnectionPool.java:86)
 	at io.vertx.sqlclient.impl.PoolBase.acquire(PoolBase.java:137)
 	at io.vertx.sqlclient.impl.PoolBase.schedule(PoolBase.java:114)
 	at io.vertx.sqlclient.impl.QueryExecutor.executeBatchQuery(QueryExecutor.java:218)
 	at io.vertx.sqlclient.impl.SqlClientBase$PreparedQueryImpl.executeBatch(SqlClientBase.java:166)
 	at io.vertx.sqlclient.impl.SqlClientBase$PreparedQueryImpl.executeBatch(SqlClientBase.java:155)
```

Should this be fixed in 4.0.1 SNAPSHOT?
I'm just using the 4.0.1 snapshot for io.vertx:vertx-mysql-client.   Should I use for any other library?

Kind regards

**Comment by vietj** [comment] 2021-02-02 13:29
we are investigating.

**Comment by underkin** [comment] 2021-02-02 13:36
Forget what I said for now. I need to repeat my test to make sure it actually fails.

**Comment by underkin** [comment] 2021-02-02 14:00
I verified now. And still getting the error when running from a worker thread.

`2021-02-02 13:53:29,193 [vert.x-worker-thread-15] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: null
	at io.vertx.sqlclient.impl.pool.ConnectionPool.check(ConnectionPool.java:260)
	at io.vertx.sqlclient.impl.pool.ConnectionPool.doAcquire(ConnectionPool.java:103)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:78)
	at io.vertx.core.impl.WorkerContext.execute(WorkerContext.java:113)
	at io.vertx.core.impl.WorkerContext.emit(WorkerContext.java:77)
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:294)
	at io.vertx.core.impl.WorkerContext.emit(WorkerContext.java:25)
	at io.vertx.sqlclient.impl.pool.ConnectionPool.acquire(ConnectionPool.java:86)
	at io.vertx.sqlclient.impl.PoolBase.acquire(PoolBase.java:137)
	at io.vertx.sqlclient.impl.PoolBase.schedule(PoolBase.java:114)
	at io.vertx.sqlclient.impl.QueryExecutor.executeBatchQuery(QueryExecutor.java:218)
	at io.vertx.sqlclient.impl.SqlClientBase$PreparedQueryImpl.executeBatch(SqlClientBase.java:166)
	at io.vertx.sqlclient.impl.SqlClientBase$PreparedQueryImpl.executeBatch(SqlClientBase.java:155)`

Of course, if I deploy the verticle as non-worker, I don't get this error.

**Comment by vietj** [comment] 2021-02-02 15:54
can you show the full stack trace ?

**Comment by underkin** [comment] 2021-02-02 16:46
sure.

This is the full stack: 

 ```
2021-02-02 16:44:26,441 [vert.x-worker-thread-15] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
 java.lang.NullPointerException: null
 	at io.vertx.sqlclient.impl.pool.ConnectionPool.check(ConnectionPool.java:260)
 	at io.vertx.sqlclient.impl.pool.ConnectionPool.doAcquire(ConnectionPool.java:103)
 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
 	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:78)
 	at io.vertx.core.impl.WorkerContext.execute(WorkerContext.java:113)
 	at io.vertx.core.impl.WorkerContext.emit(WorkerContext.java:77)
 	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:294)
 	at io.vertx.core.impl.WorkerContext.emit(WorkerContext.java:25)
 	at io.vertx.sqlclient.impl.pool.ConnectionPool.acquire(ConnectionPool.java:86)
 	at io.vertx.sqlclient.impl.PoolBase.acquire(PoolBase.java:137)
 	at io.vertx.sqlclient.impl.PoolBase.schedule(PoolBase.java:114)
 	at io.vertx.sqlclient.impl.QueryExecutor.executeBatchQuery(QueryExecutor.java:218)
 	at io.vertx.sqlclient.impl.SqlClientBase$PreparedQueryImpl.executeBatch(SqlClientBase.java:166)
 	at io.vertx.sqlclient.impl.SqlClientBase$PreparedQueryImpl.executeBatch(SqlClientBase.java:155)
 	at jdk.internal.reflect.GeneratedMethodAccessor170.invoke(Unknown Source)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
 	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap.invoke(PojoMetaMethodSite.java:200)
 	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
 	at saturn.service.timescale.TimescaleIngestVerticle.execute(TimescaleIngestVerticle.groovy:144)
 	at saturn.service.timescale.TimescaleIngestVerticle$execute$0.callCurrent(Unknown Source)
 	at saturn.service.timescale.TimescaleIngestVerticle.execute(TimescaleIngestVerticle.groovy:61)
 	at saturn.service.timescale.TimescaleIngestVerticle.execute(TimescaleIngestVerticle.groovy)
 	at saturn.common.pollworker.AbstractBasePollWorker.poll(AbstractBasePollWorker.groovy:150)
 	at jdk.internal.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351)
 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64)
 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:160)
 	at saturn.common.pollworker.BasePollWorker$_generatePollEvent_closure7.doCall(BasePollWorker.groovy:363)
 	at jdk.internal.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
 	at groovy.lang.Closure.call(Closure.java:405)
 	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
 	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:122)
 	at com.sun.proxy.$Proxy23.handle(Unknown Source)
 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
 	at io.vertx.core.impl.WorkerContext.lambda$run$1(WorkerContext.java:102)
 	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 	at java.base/java.lang.Thread.run(Thread.java:834)
```

Note the code is in groovy so, you'll see some groove related calls in the stack.

**Comment by vietj** [comment] 2021-02-02 22:14
@underkin which vertx version ?

**Comment by vietj** [comment] 2021-02-02 22:23
@underkin if you are using vertx master, do you mind checking after this commit https://github.com/eclipse-vertx/vertx-sql-client/commit/2ef215879a8d139ff30b0dd82d6c43326f6b1e96 ?

**Closed** 2021-02-02 22:24 UTC
Labels: bug

**Comment by underkin** [comment] 2021-02-03 09:11
@vietj, Does master get published to sonatype?

**Comment by vietj** [comment] 2021-02-03 09:25
it should

**Comment by underkin** [comment] 2021-02-03 17:47
Thanks @vietj . Works fine
