### ISSUE TITLE
Check MSSQL decoder for leaks

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vertx-sql-client#759] opened 2020-09-09 21:37 UTC
I currently see that the MSSQL decoding process relies on buffer slicing instead of buffer copying.

The `TdsPacketDecoder` seems correct because it uses `readRetainedSlice` that will slice the buffer and increase the reference counting (the `TdsPacket` is a `ByteBufHolder`).

Then this packet is passed to `TdsMessageDecoder` that performs dubious operations:

- read slices of a `TdsPacket` without retaining a slice, e.g `TdsMessage#newTdsMessageFromSinglePacket(...)`
- the `TdsMessageDecoder` never passes a message to a next handler instead it is handled to the `decodeMessage`

It seems to follow what the `PgDecoder` does, but the `PgDecoder` operates on the original direct `ByteBuf` and only read / copy the data when necessary and never makes slices or uses reference counting (because the only referenced counted object is the original `ByteBuf` and it is released after use).

It seems that we should either follow what the `PgDecoder` does and use a single decoder, or that we should be cautious with the buffer management being done and have a review to check whether these concerns are valid.

**Comment by tsegismont** [comment] 2020-09-10 09:01
Will look into it. Could be fixed together with #758

**Comment by tsegismont** [comment] 2021-05-26 17:11
Closing as duplicate of #926

**Closed by tsegismont** 2021-05-26 17:11 UTC
Labels: duplicate, module:mssql
