### ISSUE TITLE
reactive pgclient preparedStatement.createStream().toFlowable() doesn't emit entries onNext()

### ISSUE THREAD

**Issue by ashertarno** [eclipse-vertx/vertx-sql-client#772] opened 2020-09-22 13:23 UTC
this behavior looks like a regression in version 3.9.3.

Rxfied createStream().toFlowable() will return Flowable.onComplete() without any onNext()

in 3.9.2 all worked as expected.

**Comment by vietj** [comment] 2020-09-22 16:27
do you have a reproducer by chance ?

**Comment by vietj** [comment] 2020-09-22 16:27
it seems quite basic though

**Comment by vietj** [comment] 2020-09-22 16:27
but it would help speed up resolution :-)

**Comment by ashertarno** [comment] 2020-09-23 07:18
let's try the one from examples, any reproducer requires prerequisites like a running db and a table to query...
`Flowable<Row> flowable = pool.rxBegin() // Cursors require a transaction
  .flatMapPublisher(tx -> tx.rxPrepare("SELECT * FROM users WHERE first_name LIKE $1")
    .flatMapPublisher(preparedQuery -> {
      // Fetch 50 rows at a time
      RowStream<Row> stream = preparedQuery.createStream(50, Tuple.of("julien"));
      return stream.toFlowable();
    })
    // Commit the transaction after usage
    .doAfterTerminate(tx::commit));

// Then subscribe
flowable.subscribe(
     row -> { System.out.println("User: " + row.getString("last_name")); }, 
     err -> { System.out.println("Error: " + err.getMessage()); }, 
     () -> { System.out.println("End of stream"); }
);
`

**Comment by ashertarno** [comment] 2020-09-23 07:20
`Flowable<Row> flowable = pool.rxBegin() // Cursors require a transaction
  .flatMapPublisher(tx -> tx.rxPrepare("SELECT * FROM users WHERE first_name LIKE $1")
    .flatMapPublisher(preparedQuery -> {
      // Fetch 50 rows at a time
      RowStream<Row> stream = preparedQuery.createStream(50, Tuple.of("julien"));
      return stream.toFlowable();
    })
    // Commit the transaction after usage
    .doAfterTerminate(tx::commit));

// Then subscribe
flowable.subscribe(
     row -> { System.out.println("User: " + row.getString("last_name")); }, 
     err -> { System.out.println("Error: " + err.getMessage()); }, 
     () -> { System.out.println("End of stream"); }
);`

**Comment by vietj** [comment] 2020-09-25 08:02
thanks

**Comment by ashertarno** [comment] 2020-09-25 09:32
this will let you work without a need to create tables, etc.
`pool.rxBegin() 
            .flatMapPublisher(tx -> tx.rxPrepare("SELECT nspname FROM pg_catalog.pg_namespace")
                .flatMapPublisher(preparedQuery -> preparedQuery.createStream(2, Tuple.tuple()).toFlowable())
                .doAfterTerminate(tx::commit))
            .subscribe(next -> System.out.println(next.getString(0)), Throwable::printStackTrace, () -> System.out.println("done"));
`

**Comment by vietj** [comment] 2020-09-25 09:36
closing this issue because this project does not handle RX and it is a side effect of this issue https://github.com/eclipse-vertx/vertx-sql-client/issues/778

**Comment by vietj** [comment] 2020-09-25 09:36
well I'm still keeping it for the record as other might have encountered the same issue

**Closed** 2020-09-25 09:35 UTC
Labels: bug
