### ISSUE TITLE
link sql server Query more than 20 data exceptions

### ISSUE THREAD

**Issue by Hudiebbk** [eclipse-vertx/vertx-sql-client#1021] opened 2021-08-10 08:51 UTC
1. version 4.1.2
2. 
![image](https://user-images.githubusercontent.com/30064286/128837517-21721fc1-0980-4cd4-9460-5ad097f6209d.png)

3. jvm 11
4. 
![image](https://user-images.githubusercontent.com/30064286/128837591-326db08e-6da1-490b-a82b-16c43b649f40.png)
If there are more than 20 queries, there will be an error.

**Comment by tsegismont** [comment] 2021-08-11 14:14
Thanks for reporting @Hudiebbk 

Can you please paste in a comment:

- the `CREATE TABLE` command corresponding to `t_order`
- some sample data
- the query

This is to help reproducing. Thank you

**Comment by tsegismont** [comment] 2021-08-16 10:13
Actually, a complete reproducer (simple code and Maven POM or Gradle build file) would be better.

I read the exception more carefully and it seems the `TdsPacketDecoder` tries to get the content of a 4096 bytes-length packet (4088 + 8 bytes of headers), while available data is much less (895).
This shouldn't happen because the decoder extends Netty's `LengthFieldBasedFrameDecoder` which makes a [test for this condition](https://github.com/netty/netty/blob/netty-4.1.65.Final/codec/src/main/java/io/netty/handler/codec/LengthFieldBasedFrameDecoder.java#L425-L427).

**Comment by tsegismont** [comment] 2021-09-03 13:17
Closed in e4a543e2

**Closed by tsegismont** 2021-09-03 13:17 UTC
Labels: bug, module:mssql
