### ISSUE TITLE
Vert.x MySQL client prepared statement cache issue

### ISSUE THREAD

**Issue by singla-d11** [eclipse-vertx/vertx-sql-client#1255] opened 2022-11-10 18:53 UTC
### Version

vertx-mysql-client: `3.9.2`

### Context

While migrating from MySQL Server v5.7 to v8.023 intermittent query failures were observed with error `io.vertx.mysqlclient.MySQLException: Incorrect arguments to mysqld_stmt_execute`

Upon debugging, a bug is identified with `io.vertx.mysqlclient.impl.codec.MySQLPreparedStatement` object of `io.vertx.sqlclient.impl.command.ExtendedQueryCommand` instance.

The issue arises when a parameter value `null` is passed (optional column value in INSERT statement) in a query. Vert.x MySQL client infers its binding type as `io.vertx.mysqlclient.impl.datatype.DataType.NULL`. This binding type is used for all the values of the same column in subsequent queries. An exception `Incorrect arguments to mysqld_stmt_execute` is thrown when value of the parameter for the same column other than null is passed in subsequent queries.

### Steps to reproduce

1. Create Table on MySQL Server v8.0.23 
```
CREATE TABLE IF NOT EXISTS test_table (
  id varchar(64) NOT NULL PRIMARY KEY, 
  name varchar(64) NOT NULL, 
  description varchar(128)
);
```

2. Execute `INSERT INTO test_table (id, name, description) VALUES (?, ?, ?)` via Vert.x MySQL client with values `["b2c681d8-1890-4e34-a142-84bf0734fd54", "name-af24502e-de4c-42c4-9741-dc52b4eb7e6a", null]`

3. Execute `INSERT INTO test_table (id, name, description) VALUES (?, ?, ?)` via Vert.x MySQL client with values `["129c2e8f-52e7-4ff4-a648-ac002b18afc1", "name-900e89fc-47b5-42c7-95f5-be96f4396290", "description-1"]`

4. Exception thrown
```
io.vertx.mysqlclient.MySQLException: Incorrect arguments to mysqld_stmt_execute
 at io.vertx.mysqlclient.impl.codec.CommandCodec.handleErrorPacketPayload(CommandCodec.java:131)
 at io.vertx.mysqlclient.impl.codec.ExtendedQueryCommandBaseCodec.handleInitPacket(ExtendedQueryCommandBaseCodec.java:27)
 at io.vertx.mysqlclient.impl.codec.QueryCommandBaseCodec.decodePayload(QueryCommandBaseCodec.java:58)
 at io.vertx.mysqlclient.impl.codec.ExtendedQueryCommandCodec.decodePayload(ExtendedQueryCommandCodec.java:100)
 at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decodePacket(MySQLDecoder.java:66)
 at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decode(MySQLDecoder.java:55)
 at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
 at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
 at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
 at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
 at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.base/java.lang.Thread.run(Thread.java:834)
 ```

**Comment by tsegismont** [comment] 2022-11-29 15:29
This looks like a duplicate of #579 

It's been fixed in Vert.x 4

**Closed** 2022-11-29 15:31 UTC
Labels: duplicate
