### ISSUE TITLE
MySQL client does not correctly check if a database row value is null for prepared statement results

### ISSUE THREAD

**Issue by daihy8759** [eclipse-vertx/vertx-sql-client#350] opened 2019-07-08 08:54 UTC
when select field is null in database,  throw exception
```
    MySQLConnection.connect(vertx, options, ctx.asyncAssertSuccess(conn -> {
        conn.preparedQuery("SELECT `test_var` FROM datatype WHERE id = 3", ctx.asyncAssertSuccess(result -> {
          ctx.assertEquals(1, result.size());
          Row row = result.iterator().next();
          conn.close();
        }));
      }));
```

stack exception:
```
java.lang.IndexOutOfBoundsException: readerIndex(2) + length(1) exceeds writerIndex(2): UnpooledSlicedByteBuf(ridx: 2, widx: 2, cap: 2/2, unwrapped: PooledUnsafeDirectByteBuf(ridx: 79, widx: 90, cap: 512))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1428)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:723)
	at io.netty.buffer.AbstractByteBuf.readUnsignedByte(AbstractByteBuf.java:737)
	at io.vertx.mysqlclient.impl.util.BufferUtils.readLengthEncodedInteger(BufferUtils.java:46)
	at io.vertx.mysqlclient.impl.util.BufferUtils.readLengthEncodedString(BufferUtils.java:68)
	at io.vertx.mysqlclient.impl.codec.DataTypeCodec.binaryDecodeText(DataTypeCodec.java:350)
	at io.vertx.mysqlclient.impl.codec.DataTypeCodec.binaryDecodeBlobOrText(DataTypeCodec.java:338)
	at io.vertx.mysqlclient.impl.codec.DataTypeCodec.decodeBinary(DataTypeCodec.java:159)
```

**Comment by vietj** [comment] 2019-07-08 12:32
it looks like a bug

**Comment by vietj** [comment] 2019-07-08 12:44
can you clarify more what you observe and how to reproduce it ? you don't give enough information about it to reproduce it.

**Comment by daihy8759** [comment] 2019-07-08 12:50
just update  column value to null, empty string or not null no exception.
`UPDATE datatype set test_var = null where id =3`

**Comment by vietj** [comment] 2019-07-08 12:51
I think I was able to reproduce it

**Comment by vietj** [comment] 2019-07-08 12:51
I'll take care of it

**Comment by vietj** [comment] 2019-07-08 13:33
it should be fixed now, can you check ?

**Closed** 2019-07-08 13:32 UTC
Labels: bug

**Comment by daihy8759** [comment] 2019-07-08 14:21
🎉 yes， thanks！
