### ISSUE TITLE
Cached prepared statement do not bind the parameters before execution

### ISSUE THREAD

**Issue by DavideD** [eclipse-vertx/vertx-sql-client#719] opened 2020-07-26 12:13 UTC
I can reproduce this with Hibernate Reactive: https://github.com/hibernate/hibernate-reactive/blob/c78ee19330a655ae221e855d7cc739d2dc0e6acb/hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/SerializableExceptionTest.java

What's happening is that if I run the same query twice with different parameters, the first time the client will try to infer the data type from the parameters and then used it for the subsequent queries.
Here what's happening in my case:
We have a table `Basic` with a blob column. The first time I run an insert the Blob value for the column is null. The client will select `DataType.NULL` instead of `DataType.BLOB`. The second time I run an insert the blob parameter is not null and the client will still use `DataType.NULL` instead of `DataType.BLOB`.

This happens with version 3.9.2 and only with MySQL. It was working with 3.9.1.

The PR on Hibernate Reactive  if interested: https://github.com/hibernate/hibernate-reactive/pull/293

**Comment by BillyYccc** [comment] 2020-07-28 15:35
Thanks for reporting this, I think this is a regression due to changes of the prepared statement execution, I will investigate how to make it work again.

**Comment by gavinking** [comment] 2020-08-03 12:56
For reference, this is needed in order to resolve https://github.com/hibernate/hibernate-reactive/issues/307.

**Comment by vietj** [comment] 2020-08-12 08:54
Should be fixed by https://github.com/eclipse-vertx/vertx-sql-client/pull/729

**Closed by vietj** 2020-08-12 08:54 UTC
Labels: bug

**Comment by gavinking** [comment] 2020-08-12 09:09
> Should be fixed by https://github.com/eclipse-vertx/vertx-sql-client/pull/729

Excellent, been waiting for this one!

Any idea when we can get a release?
