### ISSUE TITLE
mysql chinese characters condition select fail

### ISSUE THREAD

**Issue by daihy8759** [eclipse-vertx/vertx-sql-client#362] opened 2019-07-17 09:04 UTC
As title say,now chinese characters condition select failed.
but before this commit : [MySQL collation support (#352)](https://github.com/eclipse-vertx/vertx-sql-client/commit/b5795163881a51794daf3fe362350740705da8a2) ,result is right.

**Comment by daihy8759** [comment] 2019-07-17 09:15
I think collation configure in MySQLConnectOptions  not very well.because table may not all collation are same,maybe use sql get collation?
```sql
SELECT TABLE_SCHEMA
    , TABLE_NAME
    , TABLE_COLLATION 
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME ='table_name';
```
![image](https://user-images.githubusercontent.com/6057326/61363275-4d8b4d80-a8b6-11e9-990b-8390f553aef8.png)
or use `show table status`

**Comment by BillyYccc** [comment] 2019-07-17 09:22
Can you give a reproducer? actually connection collation/charset is a different value from table or column collation/charset in MySQL.

**Comment by BillyYccc** [comment] 2019-07-17 09:22
You can take a look at the test as well https://github.com/eclipse-vertx/vertx-sql-client/blob/5583e1efe171a1f35e3ab9bcd8395e4c15e451fb/vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLQueryTest.java#L43-L80.

**Comment by daihy8759** [comment] 2019-07-17 09:30
```java
  @Test
  public void testTableCollation(TestContext ctx) {
    MySQLConnection.connect(vertx, options, ctx.asyncAssertSuccess(conn -> {
      conn.query("CREATE TEMPORARY TABLE chinese_city (\n" +
        "\tid INTEGER,\n" +
        "\tcity_name VARCHAR(20)) COLLATE utf8_general_ci;\n" +
        "INSERT INTO chinese_city VALUES (1, '\u5317\u4EAC');\n" +
        "INSERT INTO chinese_city VALUES (2, '\u4E0A\u6D77');\n" +
        "INSERT INTO chinese_city VALUES (3, '\u5E7F\u5DDE');\n" +
        "INSERT INTO chinese_city VALUES (4, '\u6DF1\u5733');\n" +
        "INSERT INTO chinese_city VALUES (5, '\u6B66\u6C49');\n" +
        "INSERT INTO chinese_city VALUES (6, '\u6210\u90FD');", ctx.asyncAssertSuccess(res0 -> {
        conn.preparedQuery("SELECT id, city_name FROM chinese_city where city_name=?",
          Tuple.of("北京"), ctx.asyncAssertSuccess(res1 -> {
            ctx.assertEquals(1, res1.size());
            RowIterator iterator = res1.iterator();
            conn.close();
          }));
      }));
    }));
  }
```

**Comment by BillyYccc** [comment] 2019-07-17 11:30
https://github.com/eclipse-vertx/vertx-sql-client/blob/f9c846ddeb5f1524e0711cde8217c37b7791a19e/vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandBaseCodec.java#L78 

This is where the problem happens. The param definitions in prepare statement response do not provide any useful info and charset is always `binary(63)`, I don't know why MySQL behaves like this.

**Comment by BillyYccc** [comment] 2019-07-17 12:11
It looks like JDBC MySQL is always using the UTF8 charset for the param encoding.

**Comment by BillyYccc** [comment] 2019-07-17 14:14
This should be fixed in the latest commits in https://github.com/eclipse-vertx/vertx-sql-client/pull/361.

**Closed** 2020-01-23 23:50 UTC
