### ISSUE TITLE
columns with default values

### ISSUE THREAD

**Issue by gavinking** [eclipse-vertx/vertx-sql-client#972] opened 2021-06-04 11:32 UTC
MySQL supports the `default` syntax to specify the default value of a column.

Currently, an `insert` into a table with a default column results in an error like:

```
io.vertx.mysqlclient.MySQLException: Truncated incorrect DOUBLE value: 'Davide'
	at io.vertx.mysqlclient.impl.codec.CommandCodec.handleErrorPacketPayload(CommandCodec.java:131)
	at io.vertx.mysqlclient.impl.codec.ExtendedQueryCommandBaseCodec.handleInitPacket(ExtendedQueryCommandBaseCodec.java:38)
	at io.vertx.mysqlclient.impl.codec.QueryCommandBaseCodec.decodePayload(QueryCommandBaseCodec.java:57)
	at io.vertx.mysqlclient.impl.codec.ExtendedQueryCommandCodec.decodePayload(ExtendedQueryCommandCodec.java:109)
	at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decodePacket(MySQLDecoder.java:77)
	at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decode(MySQLDecoder.java:66)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
```

I believe this is because the type of `MySQLClient.LAST_INSERTED_ID` is hardcoded to `Long`, and the column default value is interpreted as a generated id of type long.

**Comment by gavinking** [comment] 2021-06-04 11:34
Note: to reproduce this problem, all you need to do is `insert` into a table with a `default` column of type `varchar`.

**Comment by vietj** [comment] 2021-06-23 14:20
@BillyYccc does it ring a bell ?

**Comment by vietj** [comment] 2021-06-30 11:57
@BillyYccc ping

**Comment by tsegismont** [comment] 2021-08-17 16:58
I'll look into it

**Comment by tsegismont** [comment] 2021-08-18 10:01
@gavinking I couldn't reproduce.

I created this table:

```mysql
CREATE TABLE column_with_default
(
    required_column VARCHAR(500)               NOT NULL,
    optional_column VARCHAR(500) DEFAULT 'bar' NOT NULL
);
```

And wrote this test:

```java
@Test
public void testInsertWithColumnDefaultValue(TestContext ctx) {
  MySQLConnection.connect(vertx, options, ctx.asyncAssertSuccess(conn -> {
    conn.query("TRUNCATE TABLE column_with_default").execute(ctx.asyncAssertSuccess(trunc -> {
      conn.query("INSERT INTO column_with_default (required_column) VALUES ('foo')").execute(ctx.asyncAssertSuccess(insert -> {
        conn.query("SELECT required_column,optional_column FROM column_with_default").execute(ctx.asyncAssertSuccess(rows -> {
          for (Row row : rows) {
            System.out.println("row = " + row.toJson());
          }
          conn.close();
        }));
      }));
    }));
  }));
}
```

Output is:

```
row = {"required_column":"foo","optional_column":"bar"}
```

**Comment by tsegismont** [comment] 2021-09-09 16:36
@gavinking can you please confirm this is actually a bug?

**Comment by gavinking** [comment] 2021-09-09 16:40
Well, it's a bug in the design, yes. The type of `MySQLClient.LAST_INSERTED_ID` shouldn't be hardcoded to `Long`.

> And wrote this test:

In your test you're using a separate `select` statement to retrieve the generated value, but that's less efficient than using `MySQLClient.LAST_INSERTED_ID` to get it.

**Comment by gavinking** [comment] 2021-09-09 16:55
Well, wait, perhaps I've misunderstood this.

**Comment by gavinking** [comment] 2021-09-09 17:04
OK, sorry my bad, I apologize.

The problem isn't with default columns and `LAST_INSERTED_ID`, it's with a column declared as:

    fullName varchar(600) GENERATED ALWAYS AS (firstname || ' ' || lastname) STORED

and a subsequent `select` query, like what you did above.

**Comment by gavinking** [comment] 2021-09-09 17:13
create table GeneratedRegularSingleTable (id bigint not null, firstname varchar(255), fullName varchar(600) GENERATED ALWAYS AS (firstname || ' ' || lastname) STORED, lastname varchar(255), primary key (id))
    insert into GeneratedRegularSingleTable (firstname, lastname, id) values (?, ?, ?)
    select generatedp0_.id as id1_0_, generatedp0_.firstname as firstnam2_0_, generatedp0_.fullName as fullname3_0_, generatedp0_.lastname as lastname4_0_ from GeneratedRegularSingleTable generatedp0_

**Comment by tsegismont** [comment] 2021-09-10 13:38
@gavinking with this table:

```mysql
CREATE TABLE GeneratedRegularSingleTable
(
  id        BIGINT NOT NULL,
  firstname VARCHAR(255),
  fullName  VARCHAR(600) GENERATED ALWAYS AS (firstname || ' ' || lastname) STORED,
  lastname  VARCHAR(255),
  PRIMARY KEY (id)
)
```

This test passes in `master` branch:

```java
  @Test
  public void testInsertWithColumnDefaultValue(TestContext ctx) {
    MySQLConnection.connect(vertx, options, ctx.asyncAssertSuccess(conn -> {
      conn.query("TRUNCATE TABLE GeneratedRegularSingleTable").execute(ctx.asyncAssertSuccess(trunc -> {
        conn.preparedQuery("INSERT INTO GeneratedRegularSingleTable (firstname, lastname, id) VALUES (?, ?, ?)").execute(Tuple.of("John", "Doe", 1), ctx.asyncAssertSuccess(insert -> {
          conn.query("SELECT id, firstname, fullName, lastname FROM GeneratedRegularSingleTable").execute(ctx.asyncAssertSuccess(rows -> {
            for (Row row : rows) {
              System.out.println("row = " + row.toJson());
            }
            conn.close();
          }));
        }));
      }));
    }));
  }
```

```
row = {"id":1,"firstname":"John","fullName":"John Doe","lastname":"Doe"}
```

I looked again at the error message and it indicates a `VARCHAR` value was used to compare with a `DOUBLE` value. Perhaps you can point me to reproducer because I'm not sure what else I can do.

**Comment by gavinking** [comment] 2021-09-10 14:11
You can run `GeneratedPropertyMySQLTest` on this branch: https://github.com/gavinking/hibernate-reactive/tree/generated-mysql

See commit https://github.com/gavinking/hibernate-reactive/commit/87981e36aa7dfbbcad9910161fd09b1c54cf7446

**Comment by tsegismont** [comment] 2021-09-14 14:36
@gavinking I was able to reproduce.

I did some research and it seems `||` operator is the [logical `OR`](https://dev.mysql.com/doc/refman/8.0/en/logical-operators.html#operator_or) on MySQL.

If you change:

```java
@Column(columnDefinition = "varchar(600) generated always as (firstname || ' ' || lastname) stored")
```

to

```java
@Column(columnDefinition = "varchar(600) generated always as (CONCAT(firstname,' ',lastname)) stored")
```

Then the test passes.

If the MySQL user has enough privileges, you may change the SQL mode (`SET SESSION sql_mode = 'modes';`) to have `PIPES_AS_CONCAT`.

Closing as not a bug.

**Closed by tsegismont** 2021-09-14 14:36 UTC
Labels: bug, module:mysql

**Comment by gavinking** [comment] 2021-09-14 14:59
Hrm, OK, that did not occur to me.

But are you sure this isn't another case like one we had before where the SQL client is set up with strange default settings?

Because when I try from the command line SQL client, the `||` operator works without any special config (and it *is* the ANSI standard).

**Comment by gavinking** [comment] 2021-09-14 15:10
Oh wait, no, you're right. I see now. 

So the thing is that without that explicit setting `'foo' || 'bar'` is still a perfectly good expression, but evaluates to the int `0`. (Because somehow strings get coerced to zeros or something. 🤐)

So the `create table` and `select` statements run without error, but then there's an error we try to interpret that value as long.

But then in that case the actual error message here is really quite bad, and doesn't give any hint at all to what is going on. Is there any way that can be improved?

**Comment by gavinking** [comment] 2021-09-14 15:13
> But then in that case the actual error message here is really quite bad, and doesn't give any hint at all to what is going on. Is there any way that can be improved?

OK, looks like there's isn't, that's the error message from MySQL.

Fine, I feel pretty stupid now, sorry for bothering you with this.

**Comment by gavinking** [comment] 2021-09-14 15:22
Sheesh, y'know what's completely garbage about this:

    select firstname || ' ' || lastname from GeneratedRegularSingleTable;

evaluates without error and gives you a value (`0`) that can be easily coerced to `varchar`.

But when you use _the exact same expression_ in a `generated always` clause, you get that error because for some reason it can't cast `firstname` do `double` ... even though it actually needs to cast it to a logical type.

What a mess!

**Comment by tsegismont** [comment] 2021-09-14 16:01
Indeed...

And right, we can't do much about the message: when the statement is prepared MySQL replies without any error (it's valid SQL), but when it is executed, the expression can't be evaluated...
