### ISSUE TITLE
[MySQL] Reactive Client hangs after multiple calls.

### ISSUE THREAD

**Issue by olofumark** [eclipse-vertx/vertx-sql-client#724] opened 2020-08-09 08:43 UTC
This piece of code works, but starts to hang after been called a couple of times.
        Hanging persisted even with the Prepared Statement Cache disabled.
	

	String query = "SELECT * FROM tablename WHERE id = ?";
        String id = pathParamsJson.getString("id");

        mysqlPoolClient.begin(res -> {
            if (res.succeeded()) {
                Transaction tx = res.result();
                tx.preparedQuery(query).execute(Tuple.of(id), ar1 -> {
                    if (ar1.succeeded()) {
                        RowSet<Row> rows = ar1.result();
                        System.out.println("Rows Affected is: " + rows.size());
                        if (rows.size() == 1) {
                            Row row1 = rows.iterator().next();
                            JsonObject response = new JsonObject()
                                    .put("id", row1.getInteger("id"))
                                    .put("internalid", row1.getString("internalid"));
                            respond(resultHandler, response, 200);
                        } else {
                            JsonObject resultJson = new JsonObject().put("status", "notfound");
                            respond(resultHandler, resultJson, 404);    
                        }
                    } else {
                        // No need to close connection as transaction will abort and be returned to the pool
                        String failureMessage = ar1.cause().getMessage();
                        System.err.println("failureMessage:: " + failureMessage);
                        JsonObject resultJson = new JsonObject().put("status", "failure");
                        respond(resultHandler, resultJson, 500);
                    }
                });

            } else {// Failed to get connection - deal with it
                JsonObject resultJson = new JsonObject().put("status", "failure");
                respond(resultHandler, resultJson, 500);
            }
        });

**Comment by BillyYccc** [comment] 2020-08-13 00:17
hi, you need to explicitly commit or rollback the transaction using `Transaction#commit()` or `Transaction#rollback()` after execution. 
here's an example copied from the doc https://vertx.io/docs/vertx-mysql-client/java/#_simplified_transaction_api
```
private void ex01(MySQLPool mySQLPool) {
        mySQLPool.begin(ar1 -> {
            if (ar1.succeeded()) {
                Transaction tx = ar1.result();
                tx.preparedQuery("SELECT id, name FROM user")
                        .execute(ar2 -> {
                            if (ar2.succeeded()) {
                                RowSet<Row> result = ar2.result();
                                // handle the resultset here
                                // then you must explicitly commit or rollback to release the connection back to the pool
                                tx.commit(ar3 -> {
                                    if (ar3.succeeded()) {
                                        // respond with success
                                    } else {
                                        ar3.cause().printStackTrace();
                                    }
                                });
                            } else {
                                ar2.cause().printStackTrace();
                            }
                        });
            } else {
                ar1.cause().printStackTrace();
            }
        });
    }
```

**Comment by olofumark** [comment] 2020-08-14 17:10
Hi, Yes I commit all transactions over here. 
above code was pulled from the modified example I posted earlier in the groups.

**Comment by vietj** [comment] 2020-08-28 08:01
@BillyYccc what's your opinion on this issue ?

**Comment by BillyYccc** [comment] 2020-08-28 13:48
I'm unable to reproduce this last time, I will have another try.

**Comment by BillyYccc** [comment] 2020-12-12 01:02
I tried again to use the above snippet but still didn't get the result, can you upload a small full reproducer project and give the steps to reproduce?

**Comment by vietj** [comment] 2021-02-23 09:11
This looks like a duplicate of https://github.com/eclipse-vertx/vertx-sql-client/pull/835/files that was fixed, I'll close this issue. Please reopen with a reproducer if it happens again.

**Closed by vietj** 2021-02-23 09:11 UTC
Labels: bug, module:mysql
