### ISSUE TITLE
JSON not serialized in prepared reactive query

### ISSUE THREAD

**Issue by agschaid** [eclipse-vertx/vertx-sql-client#270] opened 2019-04-18 04:56 UTC
Hi,

I am not sure if this is a bug report or a question.

For reasons we are currently trying to use a psql table with a single JSON column and some constraints on the `id` field of the data:

```
CREATE TABLE contracts (
    json JSONB NOT NULL,
    CONSTRAINT validate_id CHECK( json ? 'id' )
);

CREATE UNIQUE INDEX contracts_ids_idx ON contracts( (json ->> 'id') );
```
Our relevant Java code (including code for a non-prepared version) in the respective write routine looks like this:

```
import io.reactiverse.reactivex.pgclient.PgPool;
import io.reactiverse.reactivex.pgclient.data.Json;
import io.vertx.core.json.JsonObject;

public class ContractRepository {

    private final PgPool pool; //instantiated outside the posted code

    private static final String CREATE_QUERY = "INSERT INTO contracts (json) VALUES ($1);";
    private static final String CREATE_QUERY_NOT_PREPARED = "INSERT INTO contracts (json) VALUES ('%s');";

    public Single<UUID> rxStoreNewContract(Contract contract) {

        UUID uuid = contract.getId();

        return Single.just(contract)
              .map(JsonObject::mapFrom)
              .map(Json::create)
              .flatMap( foo -> pool.rxPreparedQuery(CREATE_QUERY, Tuple.of(foo)) )
              //.flatMap(foo -> pool.rxQuery(String.format(CREATE_QUERY_NOT_PREPARED, foo)))
              .map(ar -> uuid);
    }
}
```
The non-prepared commented version works fine. 
And if I run this code and inspect `foo` in the debugger, it looks fine too (see attached screenshot).
![contract_in_reactivePg](https://user-images.githubusercontent.com/13313253/56337361-23d26580-61a5-11e9-9613-f0afd86c4bd8.png)

But the db complains about a `null` value in the `json` column:
```
06:42:59.688 [vert.x-eventloop-thread-0] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: null value in column "json" violates not-null constraint
io.reactiverse.pgclient.PgException: null value in column "json" violates not-null constraint
	at io.reactiverse.pgclient.impl.QueryCommandBase.handleErrorResponse(QueryCommandBase.java:65)
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.decodeError(MessageDecoder.java:253)
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.decodeMessage(MessageDecoder.java:142)
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.channelRead(MessageDecoder.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

I tried to trace the code in the debugger but pretty soon got lost. So I can't say if this is a bug or whether we are "holding it wrong".

We are running this in Micronaut and Micronauts preconfigured `reactive-pg-client` version is 0.10.5 . Updating to 0.10.9 didn't help and updating to 0.11.2 left us with some runtime exceptions that are probably solvable but we didn't pursue.

**Comment by agschaid** [comment] 2019-04-18 05:04
P.S.:
we have a select statement on the same column that looks quite the same
```
    private static final String SELECT_QUERY = "SELECT json FROM contracts where json->>'id'=$1";
    . . .
    // and later
   pool.rxPreparedQuery(SELECT_QUERY, Tuple.of(id.toString()))
```
and works fine. That's why I suspect that the problem is confined to JSON.

**Comment by agschaid** [comment] 2019-04-18 05:07
Also we tried various attempts to serialize it differently and to write an already serialized version of the contract. The latter of course resulted the String to be written as a single String field and thus the `validate_id` constraint in postgres failed.

**Comment by vietj** [comment] 2019-04-24 08:08
can you provide a reproducer test @agschaid ?

**Comment by agschaid** [comment] 2019-05-09 08:40
hi @vietj ,

I've set up a little Micronaut project to demonstrate the problem: [Link](https://github.com/agschaid/literate-pancake)

First I have to clarify an error on my part: when creating the issue I was a little overworked and mixed up the Error-Message and the Code that caused it. The `null value in column "json" violates not-null constraint` was not actually our problem anymore. That one was caused by us trying to turn the json object into a string, resulting it to be written to the DB as a °drum roll° string, which of course has no `id` field.

Our actual problem is that we get a `RuntimeException` with the message `Values [null] cannot be coerced to [Json]` when trying to write to the db.
Please consider [the test](https://github.com/agschaid/literate-pancake/blob/master/src/test/java/agschaid/reactivepg/storage/ContractRepositoryTest.java) I've written.

We currently work around the problem by not using prepared statements. But of course that's a major itch ;)

Any help would be very appreciated.

And as noted: we don't know if this is a bug or if we just do something wrong . . .

**Comment by vietj** [comment] 2019-05-09 12:13
thanks @agschaid

**Comment by perttuk** [comment] 2019-06-08 11:48
I had the same error and fixed it using `addJson` method, like this:

```
public Mono<PgRowSet> insert(String flow) {
	JsonObject jsonObject = new JsonObject(flow);
	Json json = Json.create(jsonObject);
	Tuple args = Tuple.tuple().addJson(json);
	return RxJava2Adapter.singleToMono(pgPool.rxPreparedQuery(INSERT_FLOW_SQL, args));
}
```

Hope this helps!

**Comment by agschaid** [comment] 2019-06-10 14:19
thanks @perttuk 

I'll try that tomorrow (both in my toy project and our production code).

**Comment by vietj** [comment] 2019-06-10 20:43
the issue is actually rather in vertx-rx that will not convert the JSON type correctly and it will be null instead.

The workaround is to do this:


```
        return Single.just(contract)
            .map(JsonObject::mapFrom)
            .map(Json::create)
            .flatMap( foo -> pool.rxPreparedQuery(CREATE_QUERY, Tuple.of(foo.getDelegate())) )
            .map( ar -> uuid);
```

the `getDelegate()` will return the correct type.

I think one solution is that Vert.x SQL Client and the Reactive PG Client should not use a codegen type for JSON and instead use a DataObject.

**Comment by vietj** [comment] 2019-06-10 20:45
Another less hackish way to make it work is to do:

```
        Single<UUID> res = Single.just(contract)
            .map(JsonObject::mapFrom)
            .map(Json::create)
            .flatMap( foo -> pool.rxPreparedQuery(CREATE_QUERY, Tuple.tuple().addJson(foo)) )
            .map(ar -> uuid);
```

**Comment by vietj** [comment] 2019-06-10 20:46
see https://github.com/eclipse-vertx/vertx-sql-client/issues/320 - I will close this issue.

**Closed by vietj** 2019-06-10 20:46 UTC
Labels: bug
