### ISSUE TITLE
The recent PR #1204 produces error in Hibernate Reactive DB2 test

### ISSUE THREAD

**Issue by blafond** [eclipse-vertx/vertx-sql-client#1208] opened 2022-06-24 15:55 UTC
### Version

4.3.2

### Context

Our nightly builds run against upcoming Vertx SQL client snapshots, in this case an error occurs in testing with **vertx-db2-client 4.3.2-SNAPSHOT**

### Do you have a reproducer?

See [build log](https://github.com/hibernate/hibernate-reactive/runs/7008005379?check_suite_focus=true#step:5:1725) for full stack trace
```
    Caused by: java.lang.IllegalStateException: Needed to have 6 in buffer but only had 0. In JDBC we would normally block here but need to find a non-blocking solution
    	at io.vertx.db2client.impl.drda.DRDAResponse.ensureALayerDataInBuffer(DRDAResponse.java:1462) ~[vertx-db2-client-4.3.2-SNAPSHOT.jar:4.3.2-SNAPSHOT]
    	at io.vertx.db2client.impl.drda.DRDAResponse.readDssHeader(DRDAResponse.java:878) ~[vertx-db2-client-4.3.2-SNAPSHOT.jar:4.3.2-SNAPSHOT]
    	at io.vertx.db2client.impl.drda.DRDAResponse.startSameIdChainParse(DRDAResponse.java:52) ~[vertx-db2-client-4.3.2-SNAPSHOT.jar:4.3.2-SNAPSHOT]
    	at io.vertx.db2client.impl.drda.DRDAQueryResponse.readDescribeInput(DRDAQueryResponse.java:81) ~[vertx-db2-client-4.3.2-SNAPSHOT.jar:4.3.2-SNAPSHOT]
    	at io.vertx.db2client.impl.drda.DRDAQueryResponse.readPrepareDescribeInputOutput(DRDAQueryResponse.java:53) ~[vertx-db2-client-4.3.2-SNAPSHOT.jar:4.3.2-SNAPSHOT]
    	at io.vertx.db2client.impl.codec.PrepareStatementCodec.decodePayload(PrepareStatementCodec.java:76) ~[vertx-db2-client-4.3.2-SNAPSHOT.jar:4.3.2-SNAPSHOT]
    	at io.vertx.db2client.impl.codec.DB2Decoder.decodePayload(DB2Decoder.java:79) ~[vertx-db2-client-4.3.2-SNAPSHOT.jar:4.3.2-SNAPSHOT]
```

**Comment by mswatosh** [comment] 2022-06-24 17:10
This looks like a duplicate of #899, which is already a known intermittent issue.

**Comment by DavideD** [comment] 2022-06-24 17:47
Ah interesting.... but it's not intermittent for us. When we launch the build it happens every time

**Comment by DavideD** [comment] 2022-06-24 17:48
It also reappeared after that specific commit, I don't know if it can helps. Anyway, I guess we can close this issue and we can comment on that one

**Comment by tsegismont** [comment] 2023-04-11 13:47
Duplicates #899

**Closed by tsegismont** 2023-04-11 13:47 UTC
Labels: bug, duplicate, module:db2
