### ISSUE TITLE
Fail to resolve MariaDB version string

### ISSUE THREAD

**Issue by AlstonTsaoTSMC** [eclipse-vertx/vertx-sql-client#1346] opened 2023-08-21 09:22 UTC
### Questions

Everytime I run a query, it shows 
```
[WARN] Incorrect parsing server tokens: java.lang.NumberFormatException: For input string: ""
```

From debugger, I found that it is due to `MySQLDatabaseMetadata.class` fail to parse the version string: "11.0.2-MariaDB-1:11.0.2+maria~ubu2204". This version string is identical to `select @@version`.

This mariadb is launched by official docker image: `docker pull mariadb:11`

### Version

Which version(s) did you encounter this bug ?

v4.4.4

### Extra

uname -a
```
Linux d15evdevvm9635 5.4.0-155-generic #172-Ubuntu SMP Fri Jul 7 16:10:02 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

java -version
```
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)
```

**Comment by vietj** [comment] 2023-08-21 12:31
looks like a duplicate of https://github.com/eclipse-vertx/vertx-sql-client/pull/1345

**Comment by tsegismont** [comment] 2023-08-22 16:37
Duplicates #1345

**Closed by tsegismont** 2023-08-22 16:37 UTC
Labels: bug, duplicate
